version: '3'

services:      
             
  php:
      image: phpmyadmin
      ports:
        - 9001:80
      environment:
        PMA_HOST: "docker_mysql_1"
        MYSQL_USERNAME: root 
        MYSQL_ROOT_PASSWORD: root
      networks:
        - docker_rede_docker
      links:
        - mysql

  mysql:
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - 3309:3306
      environment:
        MYSQL_ROOT_PASSWORD: "root"
      volumes:  
        - ./mysql/:/var/lib/mysql
      networks:
        - docker_rede_docker

networks:
  docker_rede_docker:
    driver: bridge
    


           

